[book]
authors = ["PackSixFour Devs"]
multilingual = false
src = "."
title = "eKVM"

[output.html]
git-repository-url = "https://github.com/packsixfour/ekvm"
edit-url-template = "https://github.com/packsixfour/ekvm/edit/main/docs/{path}"
site-url = "https://ekvm.dev/"

